### PR TITLE
feat: add postage_stamp_transceiver

### PR DESCRIPTION
**Pull request by Yarden-zamir**
This pull request will be merged when its done, when the following checkboxes are checked and when it passes review.

# basic checks
- [x] feature works in singleplayer
- [ ] feature works in multiplayer (verify no de-sync issues)
- [x] feature works in existing world
# feature specific checks
- [x] deletes entry from index so we can place in the same area
- [x] commands don't work in survival / without cheats enabled(require permission level 2)

### CODE REVIEW

**Comment by Yarden-zamir** [comment]
[vid](https://github.com/user-attachments/assets/17c7ed01-821e-4854-8d46-c15e10b00161)



Screenshot 2024-10-22 at 10 03 21
Screenshot 2024-10-22 at 10 05 13

**Comment by Discord-Github-Bridge** [comment]
[ **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1298180821068288020/1298182490380570635) 
> [contributors/code](https://discord.com/channels/890222432605057044/1298180821068288020/1298182490380570635)  can someone review?

**Comment by Discord-Github-Bridge** [comment]
[ **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1298180821068288020/1298182504569638973) 
> https://github.com/game-design-driven/Create-Prepare-to-Dye/pull/613/files

**Comment by Yarden-zamir** [comment]
Stuff added:
- debug commands
	- trading getPostageStamp
	- trading getTradingTransceiver
	- trading getPostageTradeAgreement
	- trading platform list

**Comment by Yarden-zamir** [comment]
Stuff added:
- debug commands
	- trading getPostageStamp
	- trading getTradingTransceiver
	- trading getPostageTradeAgreement
	- trading platform list
	- trading platform delete
- postage_stamp_transceiver item
	- right click trading terminal to send it back and get a tranciever in return so you can place it again somewhere else
	- get it from trade
		- get trade by pressing smart device

**Comment by Discord-Github-Bridge** [comment]
[ **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1298180821068288020/1298191415821471786) 
> does it need the directory `kubejs/.idea` ? Probably should of been gitignored

**Comment by Discord-Github-Bridge** [comment]
[ **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1298180821068288020/1298192861744857129) 
> currently I didn't add any settings so it's not needed but genreally it's good to have project level settings in vcs in my view. Just used webstorm with the project for the first time and it works pretty well, manages things that my swamp of javascript plugins in vscode don't

**Review by EngineerSmith — APPROVED** [review]
Looks great! I like the new commands it adds too

**Pull request merged**
